# name: Daily Git Commit and Push for Quote

# on:
#   schedule:
#     # This runs the job every day at midnight UTC
#     - cron: '05 18 * * *'  # Runs daily at midnight UTC
#   workflow_dispatch:  # Allows manual trigger of the workflow

# jobs:
#   commit_and_push:
#     runs-on: ubuntu-latest
    
#     steps:
#       # Step 1: Checkout the repository
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # Step 2: Set up Git
#       - name: Set up Git
#         run: |
#           git config --global user.name "drsnvs"
#           git config --global user.email "darshanvijaybhai@gmail.com"

#       # Step 3: Pull the latest changes from the repository
#       - name: Pull latest changes
#         run: git pull origin main  # Replace 'main' with your default branch name

#       # Step 4: Add, commit, and push changes to quote.txt
#       - name: Commit and Push changes
#         run: |
#           git add quote.txt
#           git commit -m "Update daily quote - $(date +'%Y-%m-%d')"
#           git push origin master  # Replace 'main' with your default branch name
name: Daily Quote Commit

on:
  schedule:
    - cron: '40 18 * * *'
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Call the Railway-hosted Spring Boot app to get the quote
        run: |
          curl https:quotes.up.railway.app/quote -o quote.txt

      - name: Commit and push
        run: |
          git config user.name "drsnvs"
          git config user.email "darshanvijaybhai@gmail.com"
          git add quote.txt
          git commit -m "Update daily quote $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
